/*CONTACTOS*/
export const CONTACTO_READ = 'CONTACTO_READ';
export const CONTACTO_READ_SUCCESS = 'CONTACTO_READ_SUCCESS';
export const CONTACTO_READ_ERR = 'CONTACTO_READ_ERR';

export const CONTACTO_CREATE = 'CONTACTO_CREATE';
export const CONTACTO_CREATE_SUCCESS = 'CONTACTO_CREATE_SUCCESS';
export const CONTACTO_CREATE_ERR = 'CONTACTO_CREATE_ERR';

export const CONTACTO_UPDATE = 'CONTACTO_UPDATE';
export const CONTACTO_UPDATE_SUCCESS = 'CONTACTO_UPDATE_SUCCESS';
export const CONTACTO_UPDATE_ERR = 'CONTACTO_UPDATE_ERR';

export const CONTACTO_DELETE = 'CONTACTO_DELETE';
export const CONTACTO_DELETE_SUCCESS = 'CONTACTO_DELETE_SUCCESS';
export const CONTACTO_DELETE_ERR = 'CONTACTO_DELETE_ERR';